class CreateSchedules < ActiveRecord::Migration
  def change
    create_table :schedules do |t|
      t.integer :week
      t.integer :year
      t.integer :day_one
      t.integer :day_two
      t.integer :day_three
      t.integer :day_four
      t.integer :day_five
      t.integer :day_six
      t.integer :day_seven
      t.string :d_one_nine
      t.string :d_one_ten
      t.string :d_one_eleven
      t.string :d_one_twelve
      t.string :d_one_thirteen
      t.string :d_one_fourteen
      t.string :d_one_fifteen
      t.string :d_one_sixteen
      t.string :d_one_seventeen
      t.string :d_one_eighteen
      t.string :d_one_nineteen
      t.string :d_one_twenty
      t.string :d_two_nine
      t.string :d_two_ten
      t.string :d_two_eleven
      t.string :d_two_twelve
      t.string :d_two_thirteen
      t.string :d_two_fourteen
      t.string :d_two_fifteen
      t.string :d_two_sixteen
      t.string :d_two_seventeen
      t.string :d_two_eighteen
      t.string :d_two_nineteen
      t.string :d_two_twenty
      t.string :d_three_nine
      t.string :d_three_ten
      t.string :d_three_eleven
      t.string :d_three_twelve
      t.string :d_three_thirteen
      t.string :d_three_fourteen
      t.string :d_three_fifteen
      t.string :d_three_sixteen
      t.string :d_three_seventeen
      t.string :d_three_eighteen
      t.string :d_three_nineteen
      t.string :d_three_twenty
      t.string :d_four_nine
      t.string :d_four_ten
      t.string :d_four_eleven
      t.string :d_four_twelve
      t.string :d_four_thirteen
      t.string :d_four_fourteen
      t.string :d_four_fifteen
      t.string :d_four_sixteen
      t.string :d_four_seventeen
      t.string :d_four_eighteen
      t.string :d_four_nineteen
      t.string :d_four_twenty
      t.string :d_five_nine
      t.string :d_five_ten
      t.string :d_five_eleven
      t.string :d_five_twelve
      t.string :d_five_thirteen
      t.string :d_five_fourteen
      t.string :d_five_fifteen
      t.string :d_five_sixteen
      t.string :d_five_seventeen
      t.string :d_five_eighteen
      t.string :d_five_nineteen
      t.string :d_five_twenty
      t.string :d_six_nine
      t.string :d_six_ten
      t.string :d_six_eleven
      t.string :d_six_twelve
      t.string :d_six_thirteen
      t.string :d_six_fourteen
      t.string :d_six_fifteen
      t.string :d_six_sixteen
      t.string :d_six_seventeen
      t.string :d_six_eighteen
      t.string :d_six_nineteen
      t.string :d_six_twenty
      t.string :d_seven_nine
      t.string :d_seven_ten
      t.string :d_seven_eleven
      t.string :d_seven_twelve
      t.string :d_seven_thirteen
      t.string :d_seven_fourteen
      t.string :d_seven_fifteen
      t.string :d_seven_sixteen
      t.string :d_seven_seventeen
      t.string :d_seven_eighteen
      t.string :d_seven_nineteen
      t.string :d_seven_twenty

      t.timestamps null: false
    end
  end
end
